version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/albarapp

permissions:
  - object: /home/ec2-user/albarapp
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: scripts/build_app_docker.bash
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_app_docker.bash
      timeout: 60
      runas: ec2-user
