version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/albarapp

hooks:
  AfterInstall:
    - location: scripts/build_docker.bash
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_docker.bash
      timeout: 60
      runas: ec2-user
